version: '2'

services:
  prototyped:
    image: lyseontech/quasar:v0.16.4
    container_name: prototyped
    working_dir: /var/www/app
    command: sh /var/www/app/docker-compose.sh
    volumes:
      - .:/var/www/app
    ports:
      - 8080:8080
